name: build-check-main
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v2
        with:
          distribution: "zulu"
          java-version: "11"
      - uses: subosito/flutter-action@v2
        with:
          channel: "stable"
          flutter-version: "3.3.2"
      - run: flutter pub get
      - run: flutter test
      - run: flutter build ios --release --no-codesign --dart-define=ENVIRONMENT=production
      - run: flutter build apk --dart-define=ENVIRONMENT=production
      - run: flutter build appbundle --dart-define=ENVIRONMENT=production
      - uses: actions/create-release@v1
              env:
                GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              with:
                tag_name: ${{ github.ref }}
                release_name: Release ${{ github.ref }}
                body: |
                  Changes in this Release
                  - First Change
                  - Second Change
                draft: false
                prerelease: true